# Generated by Django 5.2 on 2025-05-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], max_length=10)),
                ('src', models.URLField(max_length=500)),
                ('alt', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField(default=5000)),
                ('overlayText', models.CharField(max_length=255)),
                ('ctaText', models.CharField(max_length=100)),
                ('ctaLink', models.CharField(max_length=255)),
            ],
        ),
    ]
