# Generated by Django 5.2 on 2025-05-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_bannercontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannercontent',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='banner_media/'),
        ),
        migrations.AlterField(
            model_name='bannercontent',
            name='src',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
