# Generated by Django 5.2 on 2025-05-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_bannercontent_media_file_alter_bannercontent_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercontent',
            name='media_file',
            field=models.FileField(upload_to='banner_media/'),
        ),
    ]
