# Generated by Django 5.2 on 2025-05-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_bannercontent_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercontent',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='banner_media/'),
        ),
    ]
