# Generated by Django 5.2 on 2025-07-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_bannercontent_media_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannercontent',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='bannercontent',
            old_name='ctaText',
            new_name='cta_text',
        ),
        migrations.RenameField(
            model_name='bannercontent',
            old_name='ctaLink',
            new_name='overlay_text',
        ),
        migrations.RemoveField(
            model_name='bannercontent',
            name='overlayText',
        ),
        migrations.RemoveField(
            model_name='bannercontent',
            name='src',
        ),
        migrations.AddField(
            model_name='bannercontent',
            name='cta_link',
            field=models.CharField(default=1, help_text='e.g., /products/revitalizing-serum', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannercontent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this banner from the site without deleting it.'),
        ),
        migrations.AddField(
            model_name='bannercontent',
            name='loop_video',
            field=models.BooleanField(default=False, help_text='For videos: check if the video should loop instead of advancing.'),
        ),
        migrations.AddField(
            model_name='bannercontent',
            name='media_file_mobile',
            field=models.FileField(blank=True, help_text='Optional: Mobile version (portrait recommended). If empty, desktop version is used.', null=True, upload_to='banner_media/mobile/'),
        ),
        migrations.AddField(
            model_name='bannercontent',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which banner appears (0 first, 1 second, etc.).'),
        ),
        migrations.AlterField(
            model_name='bannercontent',
            name='alt',
            field=models.CharField(help_text='Important for SEO and accessibility.', max_length=255),
        ),
        migrations.AlterField(
            model_name='bannercontent',
            name='duration',
            field=models.PositiveIntegerField(default=7000, help_text='For images: duration in milliseconds (e.g., 7000 = 7 seconds).'),
        ),
        migrations.AlterField(
            model_name='bannercontent',
            name='media_file',
            field=models.FileField(default=1, help_text='Desktop version (landscape recommended).', upload_to='banner_media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bannercontent',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='image', max_length=10),
        ),
    ]
