# Generated by Django 5.2 on 2025-05-01 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_slug_per_parent',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_parent__0061f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_slug_da4386_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_is_feat_5928d5_idx',
        ),
    ]
