# Generated by Django 5.2 on 2025-05-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage_variant_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variant_image',
            field=models.ImageField(blank=True, null=True, upload_to='variants/'),
        ),
    ]
